version: '3.7'
services:
  db:
    build: ./docker/postgres
    volumes:
      - db-university:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=university
      - POSTGRES_PASSWORD=test
  app:
    build:
      context: ./
      dockerfile: ./docker/java/Dockerfile
    ports:
      - "8082:9095"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/university
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
volumes:
  db-university:
